In [31]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [32]:
sns.set()

In [33]:
path = 'IRIS.csv'
df = pd.read_csv(path)
df

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [34]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
X = df.iloc[:,:-1]
Y = df.iloc[:,-1]
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,train_size = 0.66)

In [35]:
scaler = MinMaxScaler()
X_train.iloc[:,:] = scaler.fit_transform(X_train.iloc[:,:])
X_test.iloc[:,:] = scaler.transform(X_test.iloc[:,:])

c:\users\anike\appdata\local\programs\python\python38\lib\site-packages\pandas\core\indexing.py:1636: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)
c:\users\anike\appdata\local\programs\python\python38\lib\site-packages\pandas\core\indexing.py:691: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value, self.name)
c:\users\anike\appdata\local\programs\python\python38\lib\site-packages\pandas\core\indexing.py:1636: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)
c:\users\anike\appdata\local\programs\python\python38\lib\site-packages\pandas\core\indexing.py:691: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value, self.name)

In [36]:
X_test

     sepal_length  sepal_width  petal_length  petal_width
20       0.285714     0.583333      0.122807     0.041667
82       0.400000     0.291667      0.508772     0.458333
68       0.514286     0.083333      0.614035     0.583333
100      0.542857     0.541667      0.877193     1.000000
149      0.428571     0.416667      0.719298     0.708333
52       0.714286     0.458333      0.684211     0.583333
103      0.542857     0.375000      0.807018     0.708333
56       0.542857     0.541667      0.649123     0.625000
67       0.400000     0.291667      0.543860     0.375000
58       0.628571     0.375000      0.631579     0.500000
35       0.171429     0.500000      0.035088     0.041667
51       0.571429     0.500000      0.614035     0.583333
5        0.285714     0.791667      0.122807     0.125000
123      0.542857     0.291667      0.684211     0.708333
66       0.342857     0.416667      0.614035     0.583333
90       0.314286     0.250000      0.596491     0.458333
129      0.800000     0.416667      0.842105     0.625000
42       0.000000     0.500000      0.052632     0.041667
4        0.171429     0.666667      0.070175     0.041667
33       0.314286     0.916667      0.070175     0.041667
69       0.342857     0.208333      0.508772     0.416667
24       0.114286     0.583333      0.157895     0.041667
1        0.142857     0.416667      0.070175     0.041667
34       0.142857     0.458333      0.087719     0.000000
134      0.485714     0.250000      0.807018     0.541667
49       0.171429     0.541667      0.070175     0.041667
32       0.228571     0.875000      0.087719     0.000000
14       0.400000     0.833333      0.035088     0.041667
142      0.400000     0.291667      0.719298     0.750000
105      0.914286     0.416667      0.982456     0.833333
115      0.571429     0.500000      0.754386     0.916667
63       0.485714     0.375000      0.649123     0.541667
92       0.400000     0.250000      0.526316     0.458333
50       0.742857     0.500000      0.649123     0.541667
128      0.571429     0.333333      0.807018     0.833333
91       0.485714     0.416667      0.631579     0.541667
40       0.171429     0.625000      0.052632     0.083333
76       0.685714     0.333333      0.666667     0.541667
141      0.714286     0.458333      0.719298     0.916667
70       0.428571     0.500000      0.666667     0.708333
13      -0.028571     0.416667      0.017544     0.000000
93       0.171429     0.125000      0.403509     0.375000
112      0.685714     0.416667      0.789474     0.833333
38       0.000000     0.416667      0.052632     0.041667
98       0.200000     0.208333      0.350877     0.416667
118      0.942857     0.250000      1.035088     0.916667
81       0.314286     0.166667      0.473684     0.375000
72       0.542857     0.208333      0.684211     0.583333
9        0.142857     0.458333      0.087719     0.000000
148      0.514286     0.583333      0.771930     0.916667
6        0.057143     0.583333      0.070175     0.083333

In [37]:
X_train['species'] = Y_train
X_test['species'] = Y_test

<ipython-input-37-aed4106aa5bf>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_train['species'] = Y_train
<ipython-input-37-aed4106aa5bf>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_test['species'] = Y_test

In [40]:
X_train

     sepal_length  sepal_width  petal_length  petal_width          species
131      1.000000     0.750000      0.947368     0.791667   Iris-virginica
74       0.571429     0.375000      0.578947     0.500000  Iris-versicolor
29       0.085714     0.500000      0.105263     0.041667      Iris-setosa
121      0.342857     0.333333      0.684211     0.791667   Iris-virginica
101      0.400000     0.291667      0.719298     0.750000   Iris-virginica
..            ...          ...           ...          ...              ...
124      0.657143     0.541667      0.824561     0.833333   Iris-virginica
122      0.942857     0.333333      1.000000     0.791667   Iris-virginica
3        0.057143     0.458333      0.087719     0.041667      Iris-setosa
125      0.800000     0.500000      0.877193     0.708333   Iris-virginica
55       0.371429     0.333333      0.614035     0.500000  Iris-versicolor

[99 rows x 5 columns]

In [26]:
X_train = pd.get_dummies(X_train,columns = ['species'])
X_test = pd.get_dummies(X_test,columns = ['species'])

In [27]:
X_train.reset_index(inplace=True,drop=True)
X_test.reset_index(inplace=True,drop=True)

In [28]:
X_train.to_csv('IRIS_train.csv',index = False,header = True)
X_test.to_csv('IRIS_test.csv',index = False,header = True)