In [20]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [21]:
sns.set()

In [22]:
path = 'IRIS.csv'
df = pd.read_csv(path)
df

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [23]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
X = df.iloc[:,:-1]
Y = df.iloc[:,-1]
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,train_size = 0.66)

In [24]:
scaler = MinMaxScaler()
X_train.iloc[:,:] = scaler.fit_transform(X_train.iloc[:,:])
X_test.iloc[:,:] = scaler.transform(X_test.iloc[:,:])

c:\users\anike\appdata\local\programs\python\python38\lib\site-packages\pandas\core\indexing.py:1636: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)
c:\users\anike\appdata\local\programs\python\python38\lib\site-packages\pandas\core\indexing.py:691: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value, self.name)
c:\users\anike\appdata\local\programs\python\python38\lib\site-packages\pandas\core\indexing.py:1636: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)
c:\users\anike\appdata\local\programs\python\python38\lib\site-packages\pandas\core\indexing.py:691: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value, self.name)

In [25]:
X_test

     sepal_length  sepal_width  petal_length  petal_width
116      0.611111     0.454545      0.758621     0.708333
58       0.638889     0.409091      0.603448     0.500000
38       0.027778     0.454545      0.034483     0.041667
126      0.527778     0.363636      0.637931     0.708333
36       0.333333     0.681818      0.034483     0.041667
54       0.611111     0.363636      0.603448     0.583333
5        0.305556     0.863636      0.103448     0.125000
145      0.666667     0.454545      0.706897     0.916667
29       0.111111     0.545455      0.086207     0.041667
99       0.388889     0.363636      0.517241     0.500000
129      0.805556     0.454545      0.810345     0.625000
25       0.194444     0.454545      0.086207     0.041667
100      0.555556     0.590909      0.844828     1.000000
90       0.333333     0.272727      0.568966     0.458333
138      0.472222     0.454545      0.637931     0.708333
78       0.472222     0.409091      0.586207     0.583333
39       0.222222     0.636364      0.068966     0.041667
133      0.555556     0.363636      0.689655     0.583333
62       0.472222     0.090909      0.500000     0.375000
108      0.666667     0.227273      0.810345     0.708333
102      0.777778     0.454545      0.827586     0.833333
134      0.500000     0.272727      0.775862     0.541667
16       0.305556     0.863636      0.034483     0.125000
92       0.416667     0.272727      0.500000     0.458333
132      0.583333     0.363636      0.775862     0.875000
114      0.416667     0.363636      0.689655     0.958333
21       0.222222     0.772727      0.068966     0.125000
86       0.666667     0.500000      0.620690     0.583333
61       0.444444     0.454545      0.534483     0.583333
30       0.138889     0.500000      0.086207     0.041667
74       0.583333     0.409091      0.551724     0.500000
112      0.694444     0.454545      0.758621     0.833333
117      0.944444     0.818182      0.965517     0.875000
70       0.444444     0.545455      0.637931     0.708333
8        0.027778     0.409091      0.051724     0.041667
32       0.250000     0.954545      0.068966     0.000000
89       0.333333     0.227273      0.500000     0.500000
69       0.361111     0.227273      0.482759     0.416667
88       0.361111     0.454545      0.517241     0.500000
15       0.388889     1.090909      0.068966     0.125000
24       0.138889     0.636364      0.137931     0.041667
76       0.694444     0.363636      0.637931     0.541667
146      0.555556     0.227273      0.672414     0.750000
66       0.361111     0.454545      0.586207     0.583333
51       0.583333     0.545455      0.586207     0.583333
53       0.333333     0.136364      0.500000     0.500000
46       0.222222     0.818182      0.086207     0.041667
59       0.250000     0.318182      0.482759     0.541667
9        0.166667     0.500000      0.068966     0.000000
22       0.083333     0.727273     -0.017241     0.041667
105      0.916667     0.454545      0.948276     0.833333

In [27]:
X_train['species'] = Y_train
X_test['species'] = Y_test

<ipython-input-27-aed4106aa5bf>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_train['species'] = Y_train
<ipython-input-27-aed4106aa5bf>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_test['species'] = Y_test

In [29]:
X_train = pd.get_dummies(X_train,columns = ['species'])
X_test = pd.get_dummies(X_test,columns = ['species'])

In [33]:
X_train.to_csv('IRIS_train.csv',index = False,header = True)
X_test.to_csv('IRIS_test.csv',index = False,header = True)